spring:
  redis:
      host: 127.0.0.1
      port: 6379
      jedis:
          pool:
              # 最大活跃连接数
              max-active: 100
              # 最大空闲连接数
              max-idle: 10
              # 最小空闲连接数
              min-idle: 0
              # 最大阻塞等待时间(负数表示没有限制)
              max-wait: -1ms
